Repository stegos/stegos, pull requests merged in 2019-10, with the labels that each got.

#1338 Resolve network name in cli from node config.
  node/src/api.rs
  node/src/lib.rs
  node/src/test/mod.rs
  src/bin/stegos/console.rs
  src/bin/stegos/main.rs
  src/bin/stegosd/main.rs
Labels: configuration

#1353 Use system resolver in windows.
  Cargo.lock
  Cargo.toml
  network/Cargo.toml
  network/src/config.rs
  network/src/libp2p_network/mod.rs
  src/bin/stegosd/main.rs
Labels: bug

#1354 Ignore cargo-audit error.
  .gitlab-ci.yml
Labels: bug

#1352 Fix handling of EOF in all Tokio streams
  blockchain/src/block.rs
  blockchain/src/blockchain.rs
  node/src/lib.rs
  node/src/test/mod.rs
  wallet/src/lib.rs
  wallet/src/snowball/mod.rs
Labels: bug

#1351 Enable logging to DATA_DIR/stegosd.log by default
  .gitignore
  src/bin/stegosd/main.rs
Labels: configuration

#1358 Update version of our for of resolver.
  Cargo.lock
  network/src/libp2p_network/mod.rs
Labels: bug, network

#1361 Fix panic in validator_activity map
  blockchain/src/block.rs
  blockchain/src/blockchain.rs
  blockchain/src/validation.rs
Labels: bug

#1359 Fix balances after 24-word recovery
  wallet/src/lib.rs
Labels: bug, wallet

#1303 Fast synchronization protocol
  Cargo.lock
  blockchain/src/block.rs
  network/Cargo.toml
  network/src/lib.rs
  network/src/libp2p_network/mod.rs
  network/src/loopback.rs
  network/src/replication/behavior.rs
  network/src/replication/handler.rs
  network/src/replication/mod.rs
  network/src/replication/protocol.rs
  node/Cargo.toml
  node/protos/replication.proto
  node/src/api.rs
  node/src/config.rs
  node/src/lib.rs
  node/src/loader.rs
  node/src/replication/api.rs
  node/src/replication/mod.rs
  node/src/replication/peer.rs
  node/src/replication/protos.rs
  node/src/test/mod.rs
  src/bin/stegos/console.rs
  src/bin/stegosd/main.rs
  testing/node01/stegosd.toml
  testing/node05/stegosd.toml
  wallet/src/test/mod.rs
Labels: bootstrap, fast bootstrap, network

#1360 Allow deleting of sealed account.
  wallet/src/api.rs
  wallet/src/lib.rs
Labels: bug, wallet

#1363 Genesis block for Mainnet Beta4
  chains/testnet/genesis.bin
Labels: configuration

#1364 Use trust-dns resolver.
  Cargo.lock
  network/Cargo.toml
  network/src/config.rs
  network/src/libp2p_network/mod.rs
Labels: bug

#1368 Fix "entered unreachable code: Expected Connecting state"
  node/src/replication/peer.rs
Labels: bug, fast bootstrap

#1365 Fix timestamp in logs after recovery.
  wallet/src/lib.rs
  wallet/src/storage.rs
Labels: wallet

#1367 Request blocks on view_changes from the future
  blockchain/src/blockchain.rs
  consensus/src/error.rs
  consensus/src/optimistic.rs
  network/src/loopback.rs
  node/src/lib.rs
  node/src/loader.rs
  node/src/test/integration.rs
Labels: bug, consensus

#1370 Fix AAA record resolving.
  network/src/config.rs
  network/src/libp2p_network/mod.rs
  src/bin/stegosd/main.rs
Labels: bug, dns

#1372 Fix consensus panic
  consensus/src/lib.rs
  consensus/src/state.rs
  node/src/lib.rs
  node/src/test/consensus.rs
Labels: consensus

#1369 Replace buggy `bitvector` with `bit-vec`
  Cargo.lock
  Cargo.toml
  blockchain/Cargo.toml
  blockchain/src/block.rs
  blockchain/src/blockchain.rs
  blockchain/src/multisignature.rs
  blockchain/src/protos.rs
  blockchain/src/test.rs
  blockchain/src/validation.rs
  blockchain/src/view_changes.rs
  consensus/Cargo.toml
  consensus/src/optimistic.rs
  consensus/src/protos.rs
  crypto/Cargo.toml
  crypto/src/utils/mod.rs
  node/Cargo.toml
  node/src/test/microblocks.rs
  src/bin/bootstrap.rs
Labels: bug, refactoring

#1373 Fix BitVec serialization and view_change proof sending mechanism.
  blockchain/src/blockchain.rs
  blockchain/src/multisignature.rs
  blockchain/src/protos.rs
  consensus/protos/consensus.proto
  consensus/src/optimistic.rs
  consensus/src/protos.rs
  crypto/src/utils/mod.rs
  node/src/lib.rs
  node/src/test/microblocks.rs
Labels: blockchain, bug, consensus

#1374 Don't show that balance is final, if some utxo is pending.
  wallet/src/lib.rs
Labels: bug

#1380 Fix PubSub LRU cache
  network/src/pubsub/behavior.rs
Labels: bug, network

#1381 Trim traling zeros for multisigmap in ViewChangeProof
  blockchain/src/protos.rs
Labels: bug

#1375 Use Cargo to build libgmp, libmpfr, libflint
  BUILD.md
  Cargo.lock
  ci-scripts/build.sh
  crypto/Cargo.toml
  crypto/build.rs
Labels: android, build

#1383 Fix unreachable!() in replication/src/peer.rs
  node/src/replication/peer.rs
Labels: bug

#1387 Add metrics for active validators count
  .gitignore
  blockchain/src/blockchain.rs
  blockchain/src/metrics.rs
  network/src/pubsub/behavior.rs
Labels: monitoring

#1382 Update rocksdb version
  Cargo.lock
  blockchain/Cargo.toml
  blockchain/src/blockchain.rs
  ci-scripts/build.sh
  wallet/Cargo.toml
  wallet/src/storage.rs
Labels: blocked, build, windows

#1385 Handle restake transaction even when not synchronized.
  blockchain/src/transaction.rs
  node/src/lib.rs
Labels: bug

#1386 Append hash on serializing block and utxo in serde.
  blockchain/src/api.rs
  blockchain/src/block.rs
  blockchain/src/lib.rs
  blockchain/src/output.rs
Labels: api

#1388 Replace force_check flag by enum.
  blockchain/src/blockchain.rs
  blockchain/src/config.rs
  node/src/test/mod.rs
  node/src/validation.rs
  src/bin/stegosd/config.rs
  src/bin/stegosd/main.rs
  stegosd.toml.example
  testing/node01/stegosd.toml
  testing/node02/stegosd.toml
  testing/node03/stegosd.toml
  testing/node04/stegosd.toml
  testing/node05/stegosd.toml
  testing/node06/stegosd.toml
  testing/node07/stegosd.toml
  testing/stegosd.toml.j2
Labels: improvements

#1390 Set rustc nightly version to 2019-10-24
  .gitlab-ci.yml
  blockchain/src/blockchain.rs
  network/src/gatekeeper/behavior.rs
  network/src/libp2p_network/mod.rs
  node/src/test/consensus.rs
  node/src/test/microblocks.rs
  rust-toolchain
  src/bin/stegosd/main.rs
Labels: build

#1389 Add Android support
  .gitlab-ci.yml
  Cargo.lock
  ci-scripts/Dockerfile
  ci-scripts/aarch64-linux-android-rustlinker
  ci-scripts/arm-linux-androideabi
  ci-scripts/armv7a-linux-androideabi-rustlinker
  ci-scripts/build.sh
  ci-scripts/cargo-config
  ci-scripts/i686-linux-android-rustlinker
  ci-scripts/rust-toolchain
  ci-scripts/rustlinker
  ci-scripts/x86_64-linux-android-rustlinker
  crypto/Cargo.toml
Labels: android, build, ci

#1391 Fix stake metrics, introduce metrics of total and node stake.
  blockchain/src/blockchain.rs
  blockchain/src/escrow.rs
  blockchain/src/metrics.rs
  node/src/lib.rs
  node/src/metrics.rs
  testing/node01/stegosd.toml
Labels: blockchain, monitoring

#1376 Re-add transactions into mempool() during apply_macro_block()
  blockchain/src/blockchain.rs
  node/src/lib.rs
  node/src/mempool.rs
Labels: bug, mempool, node
