Repository stegos/stegos, pull requests merged in 2019-09, with the labels that each got.

#1304 Block api on unseal.
  wallet/src/lib.rs
Labels: api, wallet

#1307 Fix: Default endpoint address in CLI.
  ci-scripts/build.sh
  src/bin/stegos/main.rs
  src/bin/stegosd/main.rs
Labels: api

#1308 Downgrade CI image to ubuntu:xenial
  ci-scripts/Dockerfile
  ci-scripts/build.sh
Labels: ci

#1310 Make new account unseal faster.
  src/bin/stegosd/main.rs
  wallet/src/lib.rs
  wallet/src/test/mod.rs
Labels: api, wallet

#1314 Add information about Payment, Stake, PublicPayment balances
  wallet/src/api.rs
  wallet/src/lib.rs
  wallet/src/metrics.rs
  wallet/src/test/account_transaction.rs
Labels: api, breaking change, wallet

#1315 Implement subscription API
  Cargo.lock
  api/src/server.rs
  blockchain/Cargo.toml
  blockchain/src/awards.rs
  blockchain/src/block.rs
  blockchain/src/blockchain.rs
  blockchain/src/election.rs
  blockchain/src/output.rs
  blockchain/src/test.rs
  blockchain/src/view_changes.rs
  crypto/Cargo.toml
  crypto/src/bulletproofs/mod.rs
  crypto/src/pbc/mod.rs
  crypto/src/scc/mod.rs
  crypto/src/utils/mod.rs
  node/src/api.rs
  node/src/lib.rs
  node/src/mempool.rs
  node/src/test/integration.rs
  src/bin/stegos/console.rs
  wallet/src/lib.rs
  wallet/src/storage.rs
  wallet/src/test/account_transaction.rs
  wallet/src/test/mod.rs
Labels: api, node, wallet

#1318 Review fixes for subscription API
  api/src/lib.rs
  api/src/server.rs
  blockchain/src/awards.rs
  blockchain/src/block.rs
  blockchain/src/blockchain.rs
  blockchain/src/output.rs
  blockchain/src/slashing.rs
  blockchain/src/transaction.rs
  crypto/src/scc/mod.rs
  node/src/api.rs
  node/src/lib.rs
  node/src/test/integration.rs
  src/bin/stegos/console.rs
  wallet/src/lib.rs
Labels: api, node, refactoring

#1317 Fix unstake bug.
  wallet/src/error.rs
  wallet/src/lib.rs
  wallet/src/storage.rs
  wallet/src/test/account_transaction.rs
  wallet/src/transaction.rs
Labels: bug, wallet

#1319 Fix change tracking in show utxo command.
  wallet/src/storage.rs
Labels: wallet

#1320 Track final status of balance change notification.
  wallet/src/api.rs
  wallet/src/lib.rs
Labels: wallet

#1322 Genesis block 20190916
  chains/devnet/genesis.bin
Labels: configuration, testing

#1325 Refactor Wallet
  blockchain/src/blockchain.rs
  blockchain/src/output.rs
  blockchain/src/test.rs
  wallet/src/change.rs
  wallet/src/lib.rs
  wallet/src/test/account_transaction.rs
  wallet/src/test/mod.rs
  wallet/src/transaction.rs
Labels: refactoring, wallet

#1323 Add framing in snowball and limit size of utxo.
  crypto/src/dicemix/mod.rs
  wallet/src/snowball/mod.rs
Labels: wallet

#1316 Implement Bitcoin-like public addresses - WIP
  clear-database.sh
  crypto/src/scc/mod.rs
  src/bin/stegos/console.rs
  wallet/protos/account_log.proto
  wallet/src/api.rs
  wallet/src/error.rs
  wallet/src/lib.rs
  wallet/src/protos.rs
  wallet/src/storage.rs
  wallet/src/test/account_transaction.rs
  wallet/src/transaction.rs
Labels: api, wallet

#1326 Replace Base58 to Bech32 implementation
  Cargo.lock
  ci-scripts/build.sh
  create-testing-keys.sh
  crypto/Cargo.toml
  crypto/src/bin/bruteforce.rs
  crypto/src/bin/keys.rs
  crypto/src/bin/pbc.rs
  crypto/src/bin/vdf.rs
  crypto/src/lib.rs
  crypto/src/scc/mod.rs
  node/src/test/mod.rs
  src/bin/bootstrap.rs
  src/bin/stegos/main.rs
  src/bin/stegosd/main.rs
  src/lib.rs
  testing/node01/accounts/1/account.pkey
  testing/node02/accounts/1/account.pkey
  testing/node03/accounts/1/account.pkey
  testing/node04/accounts/1/account.pkey
  testing/node05/accounts/1/account.pkey
  testing/node06/accounts/1/account.pkey
  testing/node07/accounts/1/account.pkey
Labels: crypto, serialization

#1329 Add fix for bug with loader.
  node/src/lib.rs
Labels: wallet

#1331 Made reading public keys tolerate to whitespace and to newlines.
  Cargo.lock
  keychain/Cargo.toml
  keychain/src/keyfile.rs
Labels: crypto, wallet

#1333 Fix log info and error in build
  api/src/server.rs
  keychain/src/keyfile.rs
Labels: bug, build

#1334 Save award info at end of past epoch
  blockchain/src/blockchain.rs
Labels: api

#1335 Faster load from disk
  blockchain/protos/blockchain.proto
  blockchain/src/blockchain.rs
  blockchain/src/error.rs
  blockchain/src/escrow.rs
  blockchain/src/mvcc.rs
  blockchain/src/protos.rs
  node/src/lib.rs
Labels: blockchain

#1336 Update service award difficulty.
  blockchain/src/config.rs
  src/bin/stegosd/main.rs
Labels: configuration

#1339 Fix metrics on recovery. Also fix consitency of wites in meta table.
  blockchain/src/blockchain.rs
  blockchain/src/metrics.rs
Labels: bug

#1340 Fix award state in snapshot.
  blockchain/src/blockchain.rs
Labels: bug

#1342 Changed default `min_stake_amount` for non-mainnet chains
  src/bin/stegosd/main.rs
Labels: configuration, testing

#1346 Removed beneficiary key validation from clap
  src/bin/bootstrap.rs
Labels: bug

#1348 Use warning instead of error for stakes < min_stake_amount
  src/bin/bootstrap.rs
Labels: bug

#1349 Genesis block for Mainnet Beta 3
  chains/testnet/genesis.bin
  src/bin/stegosd/main.rs
Labels: configuration, testing
