Repository stegos/stegos, pull requests merged in 2019-02, with the labels that each got.

#407 Removed `rand` dependency from `stegos_keychain`
  Cargo.lock
  keychain/Cargo.toml
  keychain/src/lib.rs
Labels: crypto, network

#404 Implement minimal persistence
  .gitignore
  Cargo.lock
  blockchain/Cargo.toml
  blockchain/src/blockchain.rs
  blockchain/src/lib.rs
  blockchain/src/storage.rs
  clear-database.sh
  config/src/types.rs
  node/src/lib.rs
  node/src/tickets.rs
  src/stegos.rs
  testing/node01/stegos.toml
  testing/node02/stegos.toml
  testing/node03/stegos.toml
  testing/stegos.toml.j2
Labels: persistency

#412 Use Box<NetworkProvider> instead of parametrization of derived structs
  network/src/dummy_network.rs
  network/src/lib.rs
  network/src/libp2p_network/mod.rs
  node/src/lib.rs
  node/src/tickets.rs
  src/console.rs
  src/stegos.rs
  txpool/src/lib.rs
Labels: network, refactoring

#416 Unicast protocol now provides `from` field with sender's pkey
  network/src/dummy_network.rs
  network/src/lib.rs
  network/src/libp2p_network/mod.rs
  txpool/src/api.rs
  txpool/src/lib.rs
Labels: network

#419 Fix unicast sending to itself + console send support
  network/src/libp2p_network/mod.rs
  src/console.rs
Labels: network

#414 Rework Console <-> Wallet <-> TxPool <-> Node workflow
  Cargo.lock
  src/console.rs
  src/stegos.rs
  txpool/Cargo.toml
  txpool/protos/txpool.proto
  txpool/src/api.rs
  txpool/src/lib.rs
  txpool/src/messages.rs
  txpool/src/protos.rs
  wallet/Cargo.toml
  wallet/src/api.rs
  wallet/src/lib.rs
Labels: value shuffle, wallet

#421 Add minimal stakers amount.
  blockchain/src/block.rs
  blockchain/src/escrow.rs
  blockchain/src/lib.rs
  consensus/src/multisignature.rs
  node/src/election.rs
  node/src/error.rs
  node/src/lib.rs
  node/src/tickets.rs
Labels: consensus, ticket_system

#423 Fix stegos_serialization to allow any other proto files directory.
  serialization/src/build_script.rs
Labels: bug

#430 Remove unused crates from the workspace
  Cargo.lock
  Cargo.toml
  api/Cargo.toml
  api/src/lib.rs
  runtime/Cargo.toml
  runtime/src/lib.rs
  storage/Cargo.toml
  storage/src/lib.rs
Labels: refactoring

#434 Fix docker build (add libmpfr4 to final image)
  Dockerfile
Labels: bug, ci

#410 Initial bootstrap implementation.
  blockchain/src/blockchain.rs
  consensus/src/state.rs
  node/protos/loader.proto
  node/src/lib.rs
  node/src/loader.rs
  node/src/protos/mod.rs
Labels: bootstrap

#443 Allow single file as protobuf source in `build_protobuf`
  serialization/src/build_script.rs
Labels: enhancement

#446 Fix `includes` vector in case of single file input
  serialization/src/build_script.rs
Labels: bug

#420 MVP Unicast implementation
  .gitignore
  Cargo.lock
  network/Cargo.toml
  network/build.rs
  network/protos/unicast_wire_proto.proto
  network/src/lib.rs
  network/src/libp2p_network/mod.rs
  network/src/libp2p_network/proto.rs
  network/src/ncp/layer.rs
  network/src/ncp/mod.rs
  network/src/ncp/proto.rs
  network/src/ncp/protocol.rs
  network/src/peerstore/mod.rs
  network/src/unicast_send/behavior.rs
  network/src/unicast_send/handler.rs
  network/src/unicast_send/mod.rs
  network/src/unicast_send/proto.rs
  network/src/unicast_send/protocol.rs
Labels: network

#452 Allow using str in `digest`, and impl Hashable for references.
  blockchain/src/block.rs
  crypto/src/hash/mod.rs
  node/src/protos/mod.rs
Labels: bug

#453 Fix error handling in Wallet
  src/console.rs
  wallet/src/lib.rs
Labels: bug, wallet

#459 Implement mocking tyme system, and test timer.
  Cargo.lock
  blockchain/Cargo.toml
  blockchain/src/blockchain.rs
  network/Cargo.toml
  node/Cargo.toml
  node/src/lib.rs
  node/src/test/mod.rs
  node/src/test/time.rs
  node/src/tickets.rs
Labels: functional testing, qa

#465 Extract validation code from node/src/lib.rs
  blockchain/src/block.rs
  blockchain/src/error.rs
  blockchain/src/output.rs
  blockchain/src/transaction.rs
  config/src/lib.rs
  node/src/lib.rs
  node/src/validation.rs
Labels: refactoring

#458 Add new REPL commands
  keychain/src/lib.rs
  src/console.rs
  wallet/src/api.rs
  wallet/src/lib.rs
Labels: repl, wallet

#466 Fix epoch validation for sealed blocks
  blockchain/src/blockchain.rs
  node/src/lib.rs
  node/src/validation.rs
Labels: regression

#472 Add cargo audit to our CI.
  .gitlab-ci.yml
  CONTRIBUTING.md
Labels: ci

#478 Fixed a bug in storage that collect blocks in wrong order.
  blockchain/src/storage.rs
Labels: bug, persistency

#469 Add test cases for transaction validation
  blockchain/src/blockchain.rs
  blockchain/src/escrow.rs
  blockchain/src/genesis.rs
  blockchain/src/output.rs
  blockchain/src/protos.rs
  blockchain/src/transaction.rs
  node/src/bootstrap.rs
  node/src/lib.rs
  node/src/mempool.rs
  node/src/test/simple_tests.rs
  node/src/validation.rs
  wallet/src/lib.rs
  wallet/src/transaction.rs
Labels: blockchain, qa, tx

#479 Add command-line argument to select chain
  Cargo.lock
  Cargo.toml
  chains/dev/genesis0.bin
  chains/dev/genesis1.bin
  chains/testnet/genesis0.bin
  chains/testnet/genesis1.bin
  create-testing-keys.sh
  node/src/lib.rs
  src/config.rs
  src/stegos.rs
  stegos.toml.example
  testing/node01/stegos.toml
  testing/node02/stegos.toml
  testing/node03/stegos.toml
  testing/stegos.toml.j2
Labels: enhancement

#480 Fix stegos version in Docker image
  Dockerfile
Labels: ci

#484 Genesis block for testnet
  chains/testnet/genesis0.bin
  chains/testnet/genesis1.bin
Labels: testing

#491 Fix `show utxo` output
  src/console.rs
Labels: bug, wallet

#492 Fix bootstrap with pruned blocks.
  blockchain/src/blockchain.rs
  blockchain/src/storage.rs
  node/src/loader.rs
  src/stegos.rs
Labels: bug

#495 Try to load configuration file from the current directory
  src/stegos.rs
Labels: configuration

#497 Fix VRF create ticket on node without stake.
  node/src/loader.rs
  node/src/tickets.rs
Labels: bug

#489 Check genesis block during recovery.
  node/src/lib.rs
Labels: persistency

#496 Resolve seed nodes from SRV and A records.
  Cargo.lock
  Cargo.toml
  network/src/config.rs
  src/stegos.rs
Labels: network

#506 Don't print error on missing stegos-log4rs.toml file
  src/stegos.rs
Labels: configuration

#507 Configure default logging, in case of missing configuration
  src/stegos.rs
Labels: configuration

#517 Extend stack size for cargo test
  .gitlab-ci.yml
Labels: build, ci

#460 Tests for vrf system
  network/Cargo.toml
  node/src/lib.rs
  node/src/test/mod.rs
  node/src/test/vrf_tickets.rs
  node/src/tickets.rs
Labels: testing, ticket_system

#503 Update Cargo.toml
  Cargo.lock
  Cargo.toml
  blockchain/Cargo.toml
  consensus/Cargo.toml
  crypto/Cargo.toml
  keychain/Cargo.toml
  network/Cargo.toml
  node/Cargo.toml
  node/src/test/simple_tests.rs
  serialization/Cargo.toml
  txpool/Cargo.toml
  wallet/Cargo.toml
  wallet/src/lib.rs
  wallet/src/transaction.rs
Labels: build

#522 Fix chain loading limit.
  blockchain/src/blockchain.rs
Labels: bug

#525 Improve badges in README.md
  README.md
Labels: doc

#526 Set minimum stake amount.
  blockchain/src/escrow.rs
  chains/dev/genesis0.bin
  chains/dev/genesis1.bin
  node/src/bootstrap.rs
  node/src/tickets.rs
  testing/node01/stegos.pkey
  testing/node01/stegos.skey
  testing/node02/stegos.pkey
  testing/node02/stegos.skey
  testing/node03/stegos.pkey
  testing/node03/stegos.skey
Labels: configuration

#529 Genesis for 16-node testnet
  chains/testnet/genesis0.bin
  chains/testnet/genesis1.bin
Labels: configuration

#530 Fix stake count in VRF tests.
  blockchain/src/blockchain.rs
  node/src/test/mod.rs
  node/src/test/simple_tests.rs
Labels: bug, testing

#531 Added manual `release` stage to build release binaries for Linux and macOS
  .gitlab-ci.yml
Labels: ci

#498 Request chain just after node start.
  node/src/lib.rs
  node/src/loader.rs
  src/stegos.rs
Labels: bootstrap, network

#552 Rename cosi keys to network keys
  blockchain/src/blockchain.rs
  blockchain/src/genesis.rs
  blockchain/src/output.rs
  consensus/src/protos.rs
  keychain/src/lib.rs
  network/src/lib.rs
  network/src/libp2p_network/mod.rs
  network/src/unicast_send/behavior.rs
  node/src/lib.rs
  node/src/loader.rs
  node/src/test/simple_tests.rs
  node/src/test/vrf_tickets.rs
  node/src/tickets.rs
  node/src/validation.rs
  src/console.rs
  src/stegos.rs
  txpool/src/lib.rs
  wallet/src/api.rs
  wallet/src/lib.rs
Labels: refactoring

#556 Rename witnesses to validators
  blockchain/protos/blockchain.proto
  blockchain/src/block.rs
  blockchain/src/blockchain.rs
  blockchain/src/error.rs
  blockchain/src/genesis.rs
  blockchain/src/protos.rs
  blockchain/src/storage.rs
  consensus/src/multisignature.rs
  consensus/src/protos.rs
  crypto/src/pbc/secure.rs
  node/src/election.rs
  node/src/lib.rs
  node/src/protos/mod.rs
  node/src/tickets.rs
  node/src/validation.rs
Labels: refactoring

#553 Change BONDING_TIME to 15 minutes
  blockchain/src/escrow.rs
Labels: staking/unstaking

#550 Remove SealedBlockMessage
  node/protos/node.proto
  node/src/consensus.rs
  node/src/error.rs
  node/src/lib.rs
  node/src/loader.rs
  node/src/protos/mod.rs
Labels: bootstrap

#557 Added genesis block for pretestnet
  chains/pretestnet/genesis0.bin
  chains/pretestnet/genesis1.bin
  src/stegos.rs
Labels: devops, testing

#558 pretestnet -> devnet
  chains/devnet/genesis0.bin
  chains/devnet/genesis1.bin
  src/stegos.rs
Labels: configuration

#559 Implement super-transactions for ValueShuffle
  blockchain/src/transaction.rs
  crypto/protos/crypto.proto
  crypto/src/curve1174/cpt.rs
  crypto/src/curve1174/fields.rs
  crypto/src/curve1174/mod.rs
  crypto/src/dicemix/mod.rs
  crypto/src/lib.rs
  crypto/src/protos.rs
  node/src/mempool.rs
  node/src/validation.rs
Labels: blockchain, breaking change, crypto

#560 Add view_change to vrf ticket message.
  node/protos/node.proto
  node/src/protos/mod.rs
  node/src/test/vrf_tickets.rs
  node/src/tickets.rs
Labels: breaking change, vrf

#561 Choose node with lowest hash as leader.
  node/src/election.rs
  node/src/tickets.rs
Labels: breaking change, vrf

#563 Sign/check unicast packets, sent over the net
  network/protos/unicast_proto.proto
  network/src/libp2p_network/mod.rs
Labels: network

#567 Update genesis
  blockchain/src/genesis.rs
  blockchain/src/lib.rs
  blockchain/src/multisignature.rs
  chains/dev/genesis0.bin
  chains/dev/genesis1.bin
  consensus/src/lib.rs
  consensus/src/state.rs
  node/src/validation.rs
  testing/node01/stegos.pkey
  testing/node01/stegos.skey
  testing/node01/stegos.toml
  testing/node02/stegos.pkey
  testing/node02/stegos.skey
  testing/node02/stegos.toml
  testing/node03/stegos.pkey
  testing/node03/stegos.skey
  testing/node03/stegos.toml
Labels: blockchain
