Repository stegos/stegos, pull requests merged in 2019-03, with the labels that each got.

#562 Implement console command to show election status.
  Cargo.lock
  crypto/src/pbc/secure.rs
  node/Cargo.toml
  node/src/lib.rs
  node/src/tickets.rs
  src/console.rs
  src/stegos.rs
Labels: console

#572 Genesis block for the devnet
  chains/devnet/genesis0.bin
  chains/devnet/genesis1.bin
Labels: devops, testing

#569 Make `Display` print shorter public keys.
  blockchain/src/merkle.rs
  blockchain/src/output.rs
  consensus/src/state.rs
  crypto/examples/pbc.rs
  crypto/src/bulletproofs/mod.rs
  crypto/src/curve1174/cpt.rs
  crypto/src/curve1174/ecpt.rs
  crypto/src/curve1174/fields.rs
  crypto/src/curve1174/fq51.rs
  crypto/src/curve1174/mod.rs
  crypto/src/hash/mod.rs
  crypto/src/pbc/fast.rs
  crypto/src/pbc/secure.rs
  keychain/src/lib.rs
  network/src/unicast_send/behavior.rs
  node/src/lib.rs
  node/src/loader.rs
  node/src/tickets.rs
  node/src/validation.rs
  txpool/src/lib.rs
  wallet/src/transaction.rs
  wallet/src/valueshuffle/mod.rs
Labels: ux

#578 Added floodsub message tracing
  network/src/libp2p_network/mod.rs
  network/src/peerstore/mod.rs
Labels: network, testing

#584 Remove unnecessary artifacts store and build stage
  .gitlab-ci.yml
Labels: ci

#581 Use `git describe` to generate application version
  Cargo.lock
  Cargo.toml
  build.rs
  src/console.rs
  src/stegos.rs
Labels: build

#583 Add more metrics.
  Cargo.lock
  blockchain/src/blockchain.rs
  blockchain/src/metrics.rs
  consensus/Cargo.toml
  consensus/src/lib.rs
  consensus/src/metrics.rs
  consensus/src/state.rs
  node/Cargo.toml
  node/src/lib.rs
  node/src/metrics.rs
  node/src/tickets.rs
Labels: monitoring

#579 Refactor block validation code
  blockchain/src/block.rs
  blockchain/src/blockchain.rs
  blockchain/src/error.rs
  blockchain/src/genesis.rs
  blockchain/src/multisignature.rs
  node/src/error.rs
  node/src/lib.rs
  node/src/mempool.rs
  node/src/test/simple_tests.rs
  node/src/validation.rs
Labels: blockchain, refactoring

#580 Remove blocks from the memory
  blockchain/src/blockchain.rs
  blockchain/src/error.rs
  blockchain/src/storage.rs
  node/src/lib.rs
  node/src/loader.rs
  node/src/test/simple_tests.rs
  node/src/test/vrf_tickets.rs
  node/src/tickets.rs
  node/src/validation.rs
Labels: persistency

#588 Don't try process uniicast messages as broadcasts
  network/src/libp2p_network/mod.rs
Labels: network

#592 Fix a bug with chain didnt load after recover.
  blockchain/src/blockchain.rs
  node/src/loader.rs
Labels: bootstrap

#523 Request blocks from node that send future ticket.
  node/src/loader.rs
  node/src/tickets.rs
Labels: bootstrap, vrf

#590 Change default values for NetworkConfig
  network/src/config.rs
Labels: configuration

#593 Fix "Registered xxx block" message
  blockchain/src/blockchain.rs
Labels: bug, logging

#594 Remove blockchain.change_group()
  blockchain/src/blockchain.rs
  node/src/lib.rs
Labels: refactoring

#595 Add basic tests for struct Blockchain
  blockchain/src/blockchain.rs
Labels: testing

#585 Implement 'show escrow' REPL command
  Cargo.lock
  Cargo.toml
  blockchain/src/escrow.rs
  node/Cargo.toml
  node/src/lib.rs
  node/src/tickets.rs
  src/console.rs
Labels: console

#597 Added job to build static release binary
  .gitlab-ci.yml
Labels: ci

#600 Genesis block for testnet2
  chains/testnet/genesis0.bin
  chains/testnet/genesis1.bin
Labels: configuration

#450 ValueShuffle - PoC
  Cargo.lock
  README-Testing.md
  blockchain/src/transaction.rs
  crypto/src/curve1174/fields.rs
  crypto/src/curve1174/mod.rs
  crypto/src/dicemix/mod.rs
  src/console.rs
  txpool/Cargo.toml
  txpool/build.rs
  txpool/protos/txpool.proto
  txpool/src/lib.rs
  txpool/src/messages.rs
  txpool/src/protos.rs
  wallet/Cargo.toml
  wallet/examples/show_utxo_chunks.rs
  wallet/protos/valueshuffle.proto
  wallet/src/error.rs
  wallet/src/lib.rs
  wallet/src/transaction.rs
  wallet/src/valueshuffle/error.rs
  wallet/src/valueshuffle/message.rs
  wallet/src/valueshuffle/mod.rs
  wallet/src/valueshuffle/protos.rs
Labels: value shuffle

#601 Bump versions to 0.2.0
  Cargo.lock
  Cargo.toml
  blockchain/Cargo.toml
  consensus/Cargo.toml
  crypto/Cargo.toml
  keychain/Cargo.toml
  network/Cargo.toml
  node/Cargo.toml
  serialization/Cargo.toml
  txpool/Cargo.toml
  wallet/Cargo.toml
Labels: build

#603 Enable release builds for tagged commits
  .gitlab-ci.yml
Labels: ci

#610 Add random and view_change to keyblock.
  blockchain/protos/blockchain.proto
  blockchain/src/block.rs
  blockchain/src/blockchain.rs
  blockchain/src/error.rs
  blockchain/src/genesis.rs
  blockchain/src/protos.rs
  blockchain/src/storage.rs
  chains/dev/genesis0.bin
  chains/dev/genesis1.bin
  consensus/src/protos.rs
  crypto/src/utils/mod.rs
  node/src/election.rs
  node/src/lib.rs
  node/src/tickets.rs
  testing/node01/stegos.pkey
  testing/node01/stegos.skey
  testing/node01/stegos.toml
  testing/node02/stegos.pkey
  testing/node02/stegos.skey
  testing/node02/stegos.toml
  testing/node03/stegos.pkey
  testing/node03/stegos.skey
  testing/node03/stegos.toml
Labels: breaking change, vrf

#614 Fix broken dev caused by #610
  blockchain/src/blockchain.rs
  blockchain/src/genesis.rs
  crypto/src/utils/mod.rs
  node/src/test/vrf_tickets.rs
  node/src/tickets.rs
Labels: bug

#622 Fix line endings
  consensus/src/metrics.rs
  node/src/metrics.rs
Labels: refactoring

#616 Auto-commit proposed block with 2/3 signatures on timeout
  blockchain/src/blockchain.rs
  blockchain/src/multisignature.rs
  consensus/src/blockchain.rs
  crypto/src/pbc/secure.rs
  node/src/lib.rs
  node/src/metrics.rs
  node/src/test/consensus.rs
  node/src/test/loopback.rs
  node/src/test/mod.rs
  node/src/test/simple_tests.rs
  node/src/test/vrf_tickets.rs
  node/src/tickets.rs
  node/src/validation.rs
Labels: blockchain, consensus, node

#626 Moved bootstrap binary to the top-level crate
  Cargo.lock
  Cargo.toml
  create-testing-keys.sh
  node/Cargo.toml
  src/bootstrap.rs
Labels: refactoring

#624 Remove pBFT consensus for monetary blocks
  blockchain/src/block.rs
  blockchain/src/blockchain.rs
  blockchain/src/error.rs
  consensus/protos/consensus.proto
  consensus/src/blockchain.rs
  consensus/src/protos.rs
  crypto/src/hash/mod.rs
  node/src/error.rs
  node/src/lib.rs
  node/src/mempool.rs
  node/src/test/consensus.rs
  node/src/test/simple_tests.rs
  node/src/test/vrf_tickets.rs
  node/src/validation.rs
Labels: consensus

#628 Implemented explicit connection shutdown
  network/src/libp2p_network/mod.rs
  network/src/ncp/handler.rs
  network/src/ncp/layer.rs
  network/src/pubsub/handler.rs
  network/src/pubsub/layer.rs
Labels: network

#634 Encapsulate blockchain state
  blockchain/src/blockchain.rs
  node/src/lib.rs
  node/src/loader.rs
  node/src/test/consensus.rs
  node/src/test/mod.rs
  node/src/test/simple_tests.rs
  node/src/tickets.rs
  node/src/validation.rs
  src/stegos.rs
Labels: refactoring

#637 Implement multi-versioned map
  blockchain/src/blockchain.rs
  blockchain/src/lib.rs
  blockchain/src/mvcc.rs
Labels: blockchain, forks

#638 Refactor stegos_blockchain
  blockchain/src/blockchain.rs
  crypto/src/pbc/secure.rs
  node/src/lib.rs
  node/src/test/simple_tests.rs
  node/src/validation.rs
  txpool/src/lib.rs
  wallet/src/valueshuffle/mod.rs
Labels: refactoring

#640 Remove debug code optimisation.
  Cargo.toml
Labels: build, improvements

#645 Remove leader, factilitator, validators, replace view_change.
  blockchain/protos/blockchain.proto
  blockchain/src/block.rs
  blockchain/src/blockchain.rs
  blockchain/src/error.rs
  blockchain/src/genesis.rs
  blockchain/src/protos.rs
  blockchain/src/storage.rs
  chains/dev/genesis0.bin
  chains/dev/genesis1.bin
  consensus/src/protos.rs
  node/src/lib.rs
  node/src/loader.rs
  node/src/mempool.rs
  node/src/validation.rs
  testing/node01/stegos.pkey
  testing/node01/stegos.skey
  testing/node02/stegos.pkey
  testing/node02/stegos.skey
  testing/node03/stegos.pkey
  testing/node03/stegos.skey
Labels: breaking change, consensus

#648 Updated genesis block for devnet
  chains/devnet/genesis0.bin
  chains/devnet/genesis1.bin
Labels: configuration, testing

#650 Notify top-level behavior on peers disconnect
  network/src/gatekeeper/behavior.rs
  network/src/libp2p_network/mod.rs
Labels: network

#606 Added chain consistency check.
  network/src/lib.rs
  network/src/loopback.rs
  node/src/lib.rs
  node/src/test/mod.rs
  src/stegos.rs
Labels: testing

#652 Remove BLS signature from Monetary Blocks
  blockchain/protos/blockchain.proto
  blockchain/src/block.rs
  blockchain/src/blockchain.rs
  blockchain/src/genesis.rs
  blockchain/src/protos.rs
  chains/dev/genesis0.bin
  chains/dev/genesis1.bin
  node/src/lib.rs
  node/src/validation.rs
  testing/node01/stegos.pkey
  testing/node01/stegos.skey
  testing/node01/stegos.toml
  testing/node02/stegos.pkey
  testing/node02/stegos.skey
  testing/node02/stegos.toml
  testing/node03/stegos.pkey
  testing/node03/stegos.skey
  testing/node03/stegos.toml
Labels: blockchain

#656 Remove unused code.
  node/src/lib.rs
Labels: improvements

#653 Fix devnet bugs.
  blockchain/src/election.rs
  node/src/loader.rs
Labels: bug

#655 Remove almost all hard-coded constants
  blockchain/src/blockchain.rs
  blockchain/src/config.rs
  blockchain/src/election.rs
  blockchain/src/escrow.rs
  node/src/config.rs
  node/src/lib.rs
  node/src/loader.rs
  node/src/test/consensus.rs
  node/src/test/mod.rs
  node/src/test/simple_tests.rs
  node/src/tickets.rs
  node/src/validation.rs
  src/bootstrap.rs
  src/config.rs
  src/stegos.rs
  wallet/src/lib.rs
  wallet/src/transaction.rs
Labels: refactoring

#644 Implement the rollback operation for monetary blocks
  blockchain/src/blockchain.rs
  blockchain/src/escrow.rs
  blockchain/src/metrics.rs
  blockchain/src/mvcc.rs
  blockchain/src/storage.rs
Labels: blockchain

#669 Request block from last leader on timeout.
  network/src/loopback.rs
  node/src/config.rs
  node/src/lib.rs
  node/src/test/consensus.rs
Labels: bootstrap

#672 Updated genesis blocks for devnet/testnet
  chains/devnet/genesis0.bin
  chains/devnet/genesis1.bin
  chains/testnet/genesis0.bin
  chains/testnet/genesis1.bin
  src/stegos.rs
Labels: testing

#675 Suppressed gcc 'unused parameter' warnings
  crypto/build.rs
Labels: build

#677 Add metrics for lost monetary blocks.
  node/src/lib.rs
  node/src/metrics.rs
Labels: consensus

#661 fix Fq51::is_odd() corner cases
  crypto/src/curve1174/ecpt.rs
  crypto/src/curve1174/fq51.rs
Labels: crypto

#679 Added encryption to unicast send
  crypto/src/pbc/secure.rs
  network/protos/unicast_proto.proto
  network/src/libp2p_network/mod.rs
Labels: network

#682 Fix lost messages issue in Stegos PubSub
  Cargo.lock
  network/Cargo.toml
  network/src/pubsub/behavior.rs
  network/src/pubsub/handler.rs
  network/src/pubsub/metrics.rs
  network/src/pubsub/mod.rs
  network/src/pubsub/protocol.rs
Labels: network
