Repository stegos/stegos, pull requests merged in 2019-11, with the labels that each got.

#1395 Fix automated builds in Docker Hub and quay.io
  .gitlab-ci.yml
  Dockerfile
  ci-scripts/build.sh
  ci-scripts/rust-toolchain
  rust-toolchain
Labels: ci, docker

#1394 Randomize re-staking + other fixes
  network/src/replication/handler.rs
  node/src/config.rs
  node/src/lib.rs
  node/src/metrics.rs
  node/src/test/mod.rs
Labels: bug

#1396 Re-stake expired stake when node becomes synchronized
  node/src/lib.rs
Labels: bug, staking/unstaking

#1397 Fix consensus regression.
  consensus/src/state.rs
  node/src/test/consensus.rs
Labels: bug, consensus

#1398 Remove /usr/src/build after all deps are installed
  ci-scripts/Dockerfile
Labels: build, docker

#1402 Update to libp2p v0.13
  Cargo.lock
  network/Cargo.toml
  network/src/libp2p_network/mod.rs
  network/stubs/libp2p/Cargo.toml
Labels: build, docker, network

#1400 Sending committed macroblock in specific order.
  node/src/lib.rs
  node/src/test/consensus.rs
Labels: bug

#1401 Fixed mistake in `ci-scripts/Dockerfile`
  ci-scripts/Dockerfile
Labels: build, docker

#1405 Add metrics for total and active pubsub connections
  network/src/pubsub/behavior.rs
  network/src/pubsub/metrics.rs
Labels: monitoring, network

#1404 Collapse stake outputs into single during restake.
  node/src/lib.rs
Labels: refactoring, staking/unstaking

#1403 Fix service award bug.
  blockchain/src/blockchain.rs
  blockchain/src/config.rs
  blockchain/src/test.rs
  node/src/test/integration.rs
  node/src/test/mod.rs
  src/bin/stegosd/main.rs
Labels: bug, service awards

#1406 Replace "utxo" field by "output_hash".
  blockchain/src/escrow.rs
  node/src/api.rs
  node/src/lib.rs
  src/bin/stegos/console.rs
  wallet/src/api.rs
  wallet/src/lib.rs
  wallet/src/storage.rs
Labels: breaking change

#1408 Add metrics for consensus and macroblock.
  blockchain/src/awards.rs
  blockchain/src/metrics.rs
  consensus/src/metrics.rs
  consensus/src/state.rs
  node/src/lib.rs
  node/src/metrics.rs
Labels: monitoring

#1407 Create zip files with Windows binaries
  ci-scripts/build.sh
Labels: ci

#1409 Add canaries for the light nodes
  blockchain/protos/blockchain.proto
  blockchain/src/block.rs
  blockchain/src/error.rs
  blockchain/src/output.rs
  blockchain/src/protos.rs
  blockchain/src/validation.rs
  chains/dev/genesis.bin
  crypto/protos/crypto.proto
  crypto/src/protos.rs
  crypto/src/scc/mod.rs
  node/src/validation.rs
Labels: blockchain, breaking change

#1410 Update defaults
  blockchain/src/config.rs
  chains/devnet/genesis.bin
  node/src/config.rs
  src/bin/stegosd/config.rs
  src/bin/stegosd/main.rs
Labels: configuration

#1412 Fix LRU expiration
  network/src/pubsub/behavior.rs
Labels: bug, network

#1411 Introduce block cache.
  blockchain/src/block.rs
  blockchain/src/blockchain.rs
  node/src/lib.rs
  node/src/test/integration.rs
Labels: blockchain, improvements

#1414 Update parity-multihash version
  Cargo.lock
  network/Cargo.toml
Labels: build, network

#1415 Remove `.aws` part from SRV records
  src/bin/stegosd/main.rs
Labels: configuration, network

#1416 Support mainnet genesis
  chains/mainnet/genesis.bin
  src/bin/stegosd/main.rs
Labels: configuration

#1418 Remove symlink for rustlinker.
  ci-scripts/aarch64-linux-android-rustlinker
  ci-scripts/arm-linux-androideabi
  ci-scripts/armv7a-linux-androideabi-rustlinker
  ci-scripts/build.sh
  ci-scripts/i686-linux-android-rustlinker
  ci-scripts/x86_64-linux-android-rustlinker
Labels: bug, windows

#1419 Genesis blocks for `mainnet` and sandbox `testnet
  chains/mainnet/genesis.bin
  chains/testnet/genesis.bin
Labels: configuration

#1420 Update rocksdb version.
  Cargo.lock
  blockchain/Cargo.toml
  wallet/Cargo.toml
Labels: ci

#1421 Make sure check for duplicate messages doesn't affect timestamp
  network/src/pubsub/behavior.rs
Labels: bug, network

#1422 Lower PubSub LRU timeout to 1 minute
  network/src/pubsub/behavior.rs
Labels: network

#1424 Fix grcov script.
  ci-scripts/build.sh
Labels: ci

#1417 Fix rust toolchain, to use new version of gcc.
  .gitlab-ci.yml
  Cargo.lock
  Cargo.toml
  blockchain/src/timestamp.rs
  ci-scripts/build.sh
Labels: ci, windows

#1431 Fix warning info about fork, to print only info.
  node/src/lib.rs
Labels: improvements

#1430 Resend restake transactions, that stucks.
  node/src/lib.rs
Labels: bug, staking/unstaking

#1432 Fix sloppy code in serialize_utxo() in Snowball
  wallet/src/snowball/mod.rs
Labels: refactoring

#1429 Add command to stake remote node.
  src/bin/stegos/console.rs
  wallet/src/api.rs
  wallet/src/lib.rs
  wallet/src/test/mod.rs
Labels: wallet

#1433 Make PeerId persistent across restarts
  network/src/libp2p_network/mod.rs
Labels: network

#1438 Update Rust Toolchain to nightly 2019 11 25
  Dockerfile
  blockchain/benches/block.rs
  blockchain/src/blockchain.rs
  blockchain/src/escrow.rs
  build.rs
  ci-scripts/rust-toolchain
  crypto/src/hash/mod.rs
  rust-toolchain
Labels: build

#1436 Zap locked_timestamp from UTXO
  blockchain/protos/blockchain.proto
  blockchain/src/blockchain.rs
  blockchain/src/output.rs
  blockchain/src/protos.rs
  blockchain/src/test.rs
  blockchain/src/validation.rs
  node/src/mempool.rs
  node/src/validation.rs
  src/bin/bootstrap.rs
  src/bin/stegos/console.rs
  wallet/examples/show_utxo_chunks.rs
  wallet/src/api.rs
  wallet/src/lib.rs
  wallet/src/snowball/mod.rs
  wallet/src/storage.rs
  wallet/src/test/account_transaction.rs
  wallet/src/transaction.rs
Labels: breaking change

#1435 Add `accounts_info` as an alias for `list_accounts`
  src/bin/stegos/console.rs
  wallet/src/api.rs
  wallet/src/lib.rs
Labels: api
